DROP TABLE IF EXISTS Utenti;
DROP TABLE IF EXISTS Tweet;

CREATE TABLE IF NOT EXISTS Utenti(
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(30) NOT NULL,
    cognome VARCHAR(30) NOT NULL,
    data_di_nascita DATE NOT NULL,
    password VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL  
);

CREATE TABLE IF NOT EXISTS Tweet(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    data_creazione TIMESTAMP NULL DEFAULT NULL,
    data_ultima_modifica TIMESTAMP NULL DEFAULT NULL,
    id_utente INT(6) NOT NULL
);